name: Build Gradle project

on:
  push:
    branches: [feature/channel]

permissions:
  contents: read

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: touch ./src/main/resources/application.properties
      - run: echo "${{ secrets.ACTIONS_BUILD_SECRETS }}" > ./src/main/resources/application.properties
      - run: cat ./src/main/resources/application.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build